gridsuite/merge-orchestrator-server

src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorService.java
src/test/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorControllerTest.java
src/test/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorIT.java

Signed-off-by: chamseddine <chamseddine.benhamed@ensi-uma.tn>

Add missing events 

---

src/main/java/org/gridsuite/merge/orchestrator/server/CaseFetcherService.java
src/main/java/org/gridsuite/merge/orchestrator/server/MergeEventService.java
src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorController.java
src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorService.java
src/main/java/org/gridsuite/merge/orchestrator/server/dto/MergeInfos.java
src/test/java/org/gridsuite/merge/orchestrator/server/CaseFetcherServiceTest.java
src/test/java/org/gridsuite/merge/orchestrator/server/MergeInfosTest.java
src/test/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorControllerTest.java
src/test/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorIT.java

Must be merged after https://github.com/powsybl/powsybl-case/pull/45

search cases with elasticsearch

---

src/main/java/org/gridsuite/merge/orchestrator/server/CaseFetcherService.java
src/test/java/org/gridsuite/merge/orchestrator/server/CaseFetcherServiceTest.java

Signed-off-by: Slimane AMAR <slimane.amar@rte-france.com>

Remove the double encoding of the date for cases search

---

pom.xml
src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorService.java

Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>

Log parameters at startup

---

src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorConfigService.java
src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorController.java
src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorService.java
src/main/java/org/gridsuite/merge/orchestrator/server/dto/MergeConfig.java
src/test/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorControllerTest.java

Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>

Get merge configurations from REST API

---

.github/workflows/maven.yml
pom.xml
src/main/java/org/gridsuite/merge/orchestrator/server/CaseFetcherService.java
src/main/java/org/gridsuite/merge/orchestrator/server/CassandraConfig.java
src/main/java/org/gridsuite/merge/orchestrator/server/CopyToNetworkStoreService.java
src/main/java/org/gridsuite/merge/orchestrator/server/IgmQualityCheckService.java
src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorController.java
src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorService.java
src/main/java/org/gridsuite/merge/orchestrator/server/dto/IgmQualityInfos.java
src/main/java/org/gridsuite/merge/orchestrator/server/repositories/IgmQualityEntity.java
src/main/java/org/gridsuite/merge/orchestrator/server/repositories/IgmQualityRepository.java
src/main/resources/application.yaml
src/main/resources/merge_orchestrator.cql
src/test/java/org/gridsuite/merge/orchestrator/server/CaseInfosTest.java
src/test/java/org/gridsuite/merge/orchestrator/server/IgmQualityCheckServiceTest.java
src/test/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorControllerTest.java
src/test/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorIT.java

This PR use temporarly :
- integration/mergingview branch of powsybl core (version: 3.6.0-SNAPSHOT)
- fix_mergingview_loadflow branch of powsybl network store
PR https://github.com/gridsuite/deployment/pull/59 is linked to this PR and must be merged at the same time

Add igm quality check and adapt to use merging view feature

---

.github/workflows/maven.yml
src/main/java/org/gridsuite/merge/orchestrator/server/CaseFetcherService.java
src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorService.java
src/main/java/org/gridsuite/merge/orchestrator/server/dto/CaseInfos.java
src/test/java/org/gridsuite/merge/orchestrator/server/CaseFetcherServiceTest.java
src/test/java/org/gridsuite/merge/orchestrator/server/CaseInfosTest.java
src/test/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorIT.java

This branch 'align_swe_merge_orchestrator_with_real_world_conditions' is based on branch 'add_igm_quality_check_and_use_merging_view', so this PR must be merged after https://github.com/gridsuite/merge-orchestrator/pull/5

Align swe merge orchestrator with real world conditions

---

src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorService.java
src/test/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorIT.java

Signed-off-by: chamseddine <chamseddine.benhamed@ensi-uma.tn>

Make an case import for each process

---

src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorService.java
src/test/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorControllerTest.java

the igm subfield had all the igms in the range instead of just
the igms for this instant
Signed-off-by: Jon Harper <jon.harper87@gmail.com>

Fix /merges?min=&..max=..,

---

src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorController.java
src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorService.java
src/main/java/org/gridsuite/merge/orchestrator/server/NetworkConversionService.java
src/main/resources/application.yaml
src/test/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorControllerTest.java
src/test/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorIT.java
src/test/java/org/gridsuite/merge/orchestrator/server/NetworkConversionServiceTest.java

A new service allowing to export merged networks must be implemented

Addition of merge export service

---

src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorConfigService.java
src/main/java/org/gridsuite/merge/orchestrator/server/repositories/IgmEntity.java
src/main/java/org/gridsuite/merge/orchestrator/server/repositories/IgmEntityKey.java
src/main/java/org/gridsuite/merge/orchestrator/server/repositories/IgmRepository.java
src/main/java/org/gridsuite/merge/orchestrator/server/repositories/MergeEntity.java
src/main/java/org/gridsuite/merge/orchestrator/server/repositories/MergeEntityKey.java
src/main/java/org/gridsuite/merge/orchestrator/server/repositories/MergeRepository.java
src/test/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorIT.java

Signed-off-by: chamseddine <chamseddine.benhamed@ensi-uma.tn>

Delete history on process deletion

---

src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorController.java
src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorService.java
src/main/java/org/gridsuite/merge/orchestrator/server/NetworkConversionService.java
src/test/java/org/gridsuite/merge/orchestrator/server/NetworkConversionServiceTest.java

Signed-off-by: HOMER Etienne <etiennehomer@gmail.com>

Fix export files names

---

pom.xml
src/test/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorControllerTest.java
src/test/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorIT.java
src/test/java/org/gridsuite/merge/orchestrator/server/ProcessConfigControllerTest.java

Signed-off-by: AbdelHedhili <abdelsalem.hedhili@rte-france.com>

powsybl 4.0.1

---

src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorConfigService.java
src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorService.java
src/test/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorIT.java

Signed-off-by: Slimane AMAR <slimane.amar@rte-france.com>

Bug fix for igm deletion when the network import failed

---

pom.xml
src/test/java/org/gridsuite/merge/orchestrator/server/LoadFlowServiceTest.java

Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>

Migrate to PowSyBl Core 4.2.0

---

src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorService.java

Signed-off-by: HOMER Etienne <etiennehomer@gmail.com>

Fix CGM export zip name (there was a regression: we want process name, not id in the zip name)

---

src/main/resources/merge_orchestrator.sql

Signed-off-by: Jon Harper <jon.harper87@gmail.com>

Regenerate sql schema after report server integration

---

src/main/java/org/gridsuite/merge/orchestrator/server/RestResponseEntityExceptionHandler.java

Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>

Log exception as an error in RestResponseEntityExceptionHandler

---

src/main/resources/config/application.yaml

Signed-off-by: HARPER Jon <jon.harper87@gmail.com>

Add group for case.import consumer, and use standard concurrency=1

---

src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorService.java
src/main/resources/config/application.yaml

This makes it easier to avoid bugs related to the edge case of concurrency: 1
Signed-off-by: HARPER Jon <jon.harper87@gmail.com>

Switch standard consumer concurrency from 1 to 2

---

src/main/java/org/gridsuite/merge/orchestrator/server/BalancesAdjustmentService.java
src/main/java/org/gridsuite/merge/orchestrator/server/CaseFetcherService.java
src/main/java/org/gridsuite/merge/orchestrator/server/CgmesBoundaryService.java
src/main/java/org/gridsuite/merge/orchestrator/server/IgmQualityCheckService.java
src/main/java/org/gridsuite/merge/orchestrator/server/LoadFlowService.java
src/main/java/org/gridsuite/merge/orchestrator/server/MergeOrchestratorConfigService.java
src/main/java/org/gridsuite/merge/orchestrator/server/NetworkConversionService.java
src/main/resources/application-local.yaml
src/main/resources/config/application.yaml

Signed-off-by: sBouzols <sylvain.bouzols@gmail.com>

homogenize of backing services keys

---

.github/workflows/maven.yml

Signed-off-by: Abdelsalem <abdelsalem.hedhili@rte-france.com>

update clients build
